package com.otakcanary.weather.domain

/**
 * WMO Code Table 4677 — "ww" Present Weather reported from a manned station.
 * Reference: https://www.nodc.noaa.gov/archive/arc0021/0002199/1.1/data/0-data/HTML/WMO-CODE/WMO4677.HTM
 * Generated by Claude Sonnet 5 Medium
 *
 * Example usage:
 *
 * val weather = WmoPresentWeather.fromCode(63)
 * println(weather?.description) // "Rain, not freezing, continuous, moderate"
 *
 * val direct = WmoPresentWeather.RAIN_CONTINUOUS_MODERATE
 * println(direct.code) // 63
*/
enum class WmoPresentWeather(val code: Int, val description: String) {

    // ww = 00-19: No precipitation, fog, duststorm, sandstorm, drifting/blowing snow at the station
    CLOUD_DEVELOPMENT_NOT_OBSERVED(0, "Cloud development not observed or not observable"),
    CLOUDS_DISSOLVING(1, "Clouds generally dissolving or becoming less developed"),
    SKY_UNCHANGED(2, "State of sky on the whole unchanged"),
    CLOUDS_FORMING(3, "Clouds generally forming or developing"),
    VISIBILITY_REDUCED_BY_SMOKE(4, "Visibility reduced by smoke (e.g. wildfires, industrial smoke, volcanic ash)"),
    HAZE(5, "Haze"),
    WIDESPREAD_DUST(6, "Widespread dust in suspension, not raised by wind at or near the station"),
    DUST_OR_SAND_RAISED(7, "Dust or sand raised by wind at or near the station, no well-developed whirls, no storm"),
    DUST_SAND_WHIRLS(8, "Well-developed dust/sand whirl(s) seen, no duststorm or sandstorm"),
    DUSTSTORM_OR_SANDSTORM_SIGHT(9, "Duststorm or sandstorm within sight or at the station in the preceding hour"),
    MIST(10, "Mist"),
    SHALLOW_FOG_PATCHES(11, "Shallow fog or ice fog in patches"),
    SHALLOW_FOG_CONTINUOUS(12, "Shallow fog or ice fog, more or less continuous"),
    LIGHTNING_NO_THUNDER(13, "Lightning visible, no thunder heard"),
    PRECIPITATION_NOT_REACHING_GROUND(14, "Precipitation within sight, not reaching the ground or sea surface"),
    PRECIPITATION_DISTANT(15, "Precipitation within sight, reaching ground, distant (more than 5 km away)"),
    PRECIPITATION_NEARBY(16, "Precipitation within sight, reaching ground, near but not at the station"),
    THUNDERSTORM_NO_PRECIPITATION(17, "Thunderstorm, no precipitation at time of observation"),
    SQUALLS(18, "Squalls at or within sight of the station in the preceding hour or at observation time"),
    FUNNEL_CLOUD(19, "Funnel cloud(s) - tornado or waterspout"),

    // ww = 20-29: Precipitation/fog/thunderstorm during preceding hour but not at observation time
    DRIZZLE_OR_SNOW_GRAINS_PAST(20, "Drizzle (not freezing) or snow grains in preceding hour, not shower"),
    RAIN_PAST(21, "Rain (not freezing) in preceding hour, not shower"),
    SNOW_PAST(22, "Snow in preceding hour, not shower"),
    RAIN_AND_SNOW_PAST(23, "Rain and snow, or ice pellets, in preceding hour, not shower"),
    FREEZING_DRIZZLE_OR_RAIN_PAST(24, "Freezing drizzle or freezing rain in preceding hour, not shower"),
    RAIN_SHOWER_PAST(25, "Shower(s) of rain in preceding hour"),
    SNOW_SHOWER_PAST(26, "Shower(s) of snow, or rain and snow, in preceding hour"),
    HAIL_SHOWER_PAST(27, "Shower(s) of hail, or rain and hail, in preceding hour"),
    FOG_PAST(28, "Fog or ice fog in preceding hour"),
    THUNDERSTORM_PAST(29, "Thunderstorm (with or without precipitation) in preceding hour"),

    // ww = 30-39: Duststorm, sandstorm, drifting or blowing snow
    DUSTSTORM_SLIGHT_DECREASING(30, "Slight or moderate duststorm/sandstorm, decreased in preceding hour"),
    DUSTSTORM_SLIGHT_UNCHANGED(31, "Slight or moderate duststorm/sandstorm, no change in preceding hour"),
    DUSTSTORM_SLIGHT_INCREASING(32, "Slight or moderate duststorm/sandstorm, begun or increased in preceding hour"),
    DUSTSTORM_SEVERE_DECREASING(33, "Severe duststorm/sandstorm, decreased in preceding hour"),
    DUSTSTORM_SEVERE_UNCHANGED(34, "Severe duststorm/sandstorm, no change in preceding hour"),
    DUSTSTORM_SEVERE_INCREASING(35, "Severe duststorm/sandstorm, begun or increased in preceding hour"),
    BLOWING_SNOW_LOW_SLIGHT(36, "Slight or moderate blowing snow, generally below eye level"),
    BLOWING_SNOW_LOW_HEAVY(37, "Heavy drifting snow, generally below eye level"),
    BLOWING_SNOW_HIGH_SLIGHT(38, "Slight or moderate blowing snow, generally above eye level"),
    BLOWING_SNOW_HIGH_HEAVY(39, "Heavy drifting snow, generally above eye level"),

    // ww = 40-49: Fog or ice fog at time of observation
    FOG_AT_DISTANCE(40, "Fog or ice fog at a distance, extending above observer level, not at station in preceding hour"),
    FOG_PATCHES(41, "Fog or ice fog in patches"),
    FOG_SKY_VISIBLE_THINNING(42, "Fog or ice fog, sky visible, thinner than in preceding hour"),
    FOG_SKY_INVISIBLE_THINNING(43, "Fog or ice fog, sky invisible, thinner than in preceding hour"),
    FOG_SKY_VISIBLE_UNCHANGED(44, "Fog or ice fog, sky visible, no appreciable change in preceding hour"),
    FOG_SKY_INVISIBLE_UNCHANGED(45, "Fog or ice fog, sky invisible, no appreciable change in preceding hour"),
    FOG_SKY_VISIBLE_THICKENING(46, "Fog or ice fog, sky visible, begun or thicker in preceding hour"),
    FOG_SKY_INVISIBLE_THICKENING(47, "Fog or ice fog, sky invisible, begun or thicker in preceding hour"),
    FOG_DEPOSITING_RIME_VISIBLE(48, "Fog depositing rime, sky visible"),
    FOG_DEPOSITING_RIME_INVISIBLE(49, "Fog depositing rime, sky invisible"),

    // ww = 50-59: Drizzle
    DRIZZLE_INTERMITTENT_SLIGHT(50, "Drizzle, not freezing, intermittent, slight"),
    DRIZZLE_CONTINUOUS_SLIGHT(51, "Drizzle, not freezing, continuous, slight"),
    DRIZZLE_INTERMITTENT_MODERATE(52, "Drizzle, not freezing, intermittent, moderate"),
    DRIZZLE_CONTINUOUS_MODERATE(53, "Drizzle, not freezing, continuous, moderate"),
    DRIZZLE_INTERMITTENT_HEAVY(54, "Drizzle, not freezing, intermittent, heavy (dense)"),
    DRIZZLE_CONTINUOUS_HEAVY(55, "Drizzle, not freezing, continuous, heavy (dense)"),
    FREEZING_DRIZZLE_SLIGHT(56, "Drizzle, freezing, slight"),
    FREEZING_DRIZZLE_MODERATE_HEAVY(57, "Drizzle, freezing, moderate or heavy (dense)"),
    DRIZZLE_AND_RAIN_SLIGHT(58, "Drizzle and rain, slight"),
    DRIZZLE_AND_RAIN_MODERATE_HEAVY(59, "Drizzle and rain, moderate or heavy"),

    // ww = 60-69: Rain
    RAIN_INTERMITTENT_SLIGHT(60, "Rain, not freezing, intermittent, slight"),
    RAIN_CONTINUOUS_SLIGHT(61, "Rain, not freezing, continuous, slight"),
    RAIN_INTERMITTENT_MODERATE(62, "Rain, not freezing, intermittent, moderate"),
    RAIN_CONTINUOUS_MODERATE(63, "Rain, not freezing, continuous, moderate"),
    RAIN_INTERMITTENT_HEAVY(64, "Rain, not freezing, intermittent, heavy"),
    RAIN_CONTINUOUS_HEAVY(65, "Rain, not freezing, continuous, heavy"),
    FREEZING_RAIN_SLIGHT(66, "Rain, freezing, slight"),
    FREEZING_RAIN_MODERATE_HEAVY(67, "Rain, freezing, moderate or heavy (dense)"),
    RAIN_OR_DRIZZLE_AND_SNOW_SLIGHT(68, "Rain or drizzle and snow, slight"),
    RAIN_OR_DRIZZLE_AND_SNOW_MODERATE_HEAVY(69, "Rain or drizzle and snow, moderate or heavy"),

    // ww = 70-79: Solid precipitation, not showery
    SNOWFLAKES_INTERMITTENT_SLIGHT(70, "Intermittent fall of snowflakes, slight"),
    SNOWFLAKES_CONTINUOUS_SLIGHT(71, "Continuous fall of snowflakes, slight"),
    SNOWFLAKES_INTERMITTENT_MODERATE(72, "Intermittent fall of snowflakes, moderate"),
    SNOWFLAKES_CONTINUOUS_MODERATE(73, "Continuous fall of snowflakes, moderate"),
    SNOWFLAKES_INTERMITTENT_HEAVY(74, "Intermittent fall of snowflakes, heavy"),
    SNOWFLAKES_CONTINUOUS_HEAVY(75, "Continuous fall of snowflakes, heavy"),
    DIAMOND_DUST(76, "Diamond dust (with or without fog)"),
    SNOW_GRAINS(77, "Snow grains (with or without fog)"),
    ISOLATED_SNOW_CRYSTALS(78, "Isolated star-like snow crystals (with or without fog)"),
    ICE_PELLETS(79, "Ice pellets"),

    // ww = 80-99: Showery precipitation, or precipitation with current/recent thunderstorm
    RAIN_SHOWER_SLIGHT(80, "Rain shower(s), slight"),
    RAIN_SHOWER_MODERATE_HEAVY(81, "Rain shower(s), moderate or heavy"),
    RAIN_SHOWER_VIOLENT(82, "Rain shower(s), violent"),
    RAIN_SNOW_SHOWER_SLIGHT(83, "Shower(s) of rain and snow mixed, slight"),
    RAIN_SNOW_SHOWER_MODERATE_HEAVY(84, "Shower(s) of rain and snow mixed, moderate or heavy"),
    SNOW_SHOWER_SLIGHT(85, "Snow shower(s), slight"),
    SNOW_SHOWER_MODERATE_HEAVY(86, "Snow shower(s), moderate or heavy"),
    SNOW_PELLETS_SHOWER_SLIGHT(87, "Shower(s) of snow pellets or small hail, with/without rain, slight"),
    SNOW_PELLETS_SHOWER_MODERATE_HEAVY(88, "Shower(s) of snow pellets or small hail, with/without rain, moderate or heavy"),
    HAIL_SHOWER_SLIGHT(89, "Shower(s) of hail, with/without rain, not with thunder, slight"),
    HAIL_SHOWER_MODERATE_HEAVY(90, "Shower(s) of hail, with/without rain, not with thunder, moderate or heavy"),
    THUNDERSTORM_PAST_RAIN_SLIGHT(91, "Slight rain, thunderstorm in preceding hour but not now"),
    THUNDERSTORM_PAST_RAIN_MODERATE_HEAVY(92, "Moderate or heavy rain, thunderstorm in preceding hour but not now"),
    THUNDERSTORM_PAST_SNOW_SLIGHT(93, "Slight snow, rain/snow mixed, or hail, thunderstorm in preceding hour but not now"),
    THUNDERSTORM_PAST_SNOW_MODERATE_HEAVY(94, "Moderate/heavy snow, rain/snow mixed, or hail, thunderstorm in preceding hour but not now"),
    THUNDERSTORM_SLIGHT_MODERATE_NO_HAIL(95, "Thunderstorm, slight or moderate, without hail, with rain and/or snow"),
    THUNDERSTORM_SLIGHT_MODERATE_WITH_HAIL(96, "Thunderstorm, slight or moderate, with hail"),
    THUNDERSTORM_HEAVY_NO_HAIL(97, "Thunderstorm, heavy, without hail, with rain and/or snow"),
    THUNDERSTORM_WITH_DUSTSTORM(98, "Thunderstorm combined with duststorm or sandstorm"),
    THUNDERSTORM_HEAVY_WITH_HAIL(99, "Thunderstorm, heavy, with hail");

    companion object {
        private val byCode: Map<Int, WmoPresentWeather> = entries.associateBy { it.code }

        /**
         * Translates a raw WMO "ww" code figure into its enum representation.
         * Returns null if the code is outside the defined 00-99 range.
         */
        fun fromCode(code: Int): WmoPresentWeather? = byCode[code]

        /**
         * Same as [fromCode] but throws if the code is unrecognized.
         */
        fun fromCodeOrThrow(code: Int): WmoPresentWeather =
            fromCode(code) ?: throw IllegalArgumentException("Unknown WMO 4677 ww code: $code")
    }
}

